uktrade/data-store-service

tests/api/test_access_control.py, tests/api/test_utils.py, tests/api/test_views.py, tests/conftest.py
"issues"
* do we need to add an integrated test to test a real redis server instance instead of using the mock cache? I actually think the mock cache is fine and we don't need to do this because I think our get and set implementations are quite simple. On the other hand setting up a fixture to connect to and reset a redis instance is not that much work
https://github.com/uktrade/data-store-service/blob/develop/app/api/views.py#L38
* we can also combine the `app_with_hawk_user` and `app_with_mock_cache` or make the former use the latter if they are going to be used together all the time, but it would make our fixtures a little less flexible for future weird combinations of fixtures
=> add app_with_mock_cache fixture. Fix state changing test

app/commands/dev/add_hawk_user.py, app/commands/dev/datafiles_to_db_by_source.py, app/etl/etl_world_bank_tariff.py
- Reverted change to worldbank dataset name
- Fixed add_hawk_user
To test add_hawk_user run the following:
- `/manage.py dev add_hawk_user --client_id hello --client_key hello --client_scope "hello" --description hello`
The script should run successfully
=> Fix commands

app/commands/dev/datafiles_to_db_by_source.py, app/etl/etl_base.py, app/etl/etl_incremental_data.py, app/etl/etl_world_bank_tariff.py, app/etl/manager.py, tests/commands/dev/test_datafiles_to_db_by_source.py, tests/etl/test_dit_reference_postcodes.py, tests/etl/test_ons_postcode_directory.py, tests/etl/test_world_bank_tariff.py
To test:
- Run `./manage.py dev datafiles_to_db_by_source --world_bank.bulk --products 10129,1061`
Check only those two products appear in the database.
Note:
I've left the other two pipelines for now and will remove at a later date.
=> Selected products option for world bank tariff pipelines

app/db/models/external.py
When doing a fresh build the pipeline fails because the column has the incorrect name
=> Fix World bank L0 model datefile_created

.gitignore, Dockerfile, app/commands/dev/__init__.py, app/commands/dev/spire.py, app/db/models/external.py, requirements.in, requirements.txt, scripts/install_psql_client.sh, scripts/install_python_packages.sh, tests/fixtures/factories.py
Here is the initial command to populate (with tests data) and dump the spire schema
The dump command dumps all tables within the schema into csv files. This will be used to generate the test data csv files. It also has scope to be changed into a more generic command where any schema could be dumped.
The populate command is the foundations for how test data will be created using factory boy.
As more models get added this command will grow.
To test (psql is required)
- `./scripts/install_psql_client.sh`
- `./manage.py dev populate_spire_schema  --batch_size 100`
- Check database tables have been populated
- `/manage.py dev dump_spire_schema` 
- Check folder .csv/spire for csv files
Consider this first part tests and refactoring to follow and a process of using the factories within the tests …
=> Command to dump and populate spire schema

app/api/views/dit_reference_postcodes.py, tests/api/views/test_get_dit_reference_postcode.py
This fixes the issue when no postcode is specified on the `get-postcode-data` endpoint.
Before fix an internal server error is raised
=> Fix no postcode specified in search request

Makefile, app/config/gunicorn_config.py
This sets the gunicorn header rather than showing which version is being used.
To test make sure your set up uses  the `make run_server` command rather than the dev alternative. 
Go to a page and check the response headers
=> Set gunicorn server header

app/uploader/forms.py, app/uploader/templates/pipeline_data_uploaded.html, app/uploader/views.py
- show schema and table name in data workspace at the end of the user journey
- take capitalisation into account on finding existing pipelines
- replace dots from org/dataset names
=> show dw schema and table and improve input validation

.gitignore, app/uploader/templates/form/input_radio_field.html, tests/uploader/test_views.py
At the moment all of the radio inputs and labels have the same id -
`pipeline`. This means that clicking on the label of any radio button
will select the first radio in the list, because that's the first
element with the `pipeline` id. Let's use the proper ID.
=>  Fix id for pipeline select radio

app/uploader/forms.py, tests/uploader/test_views.py
The dataset will eventually fail to import if we allow freeform field
names here for the db schema and table name. Let's be a bit restrictive
here (alphanumeric, underscores, dashes, periods) to make sure that the
names are fine. We currently only expect Data Workspace team members to
be uploading data this way, so we can be a bit vague about the
requirements.
We will want to enforce the standards automatically when we release this
to more users, and we have a Trello ticket in the backlog to work on
this.
=> Prevent users from picking invalid db identifiers

Dockerfile, Makefile, scripts/compile_assets.sh
PaaS will automatically install the dependencies we need during the
staging process of the app when we deploy to PaaS. If we npm install
ourselves, it can sometimes be so slow that our app doesn't respond to
the healthcheck in time and so never becomes healthy.
=> Don't `npm install` when deploying to PaaS

Dockerfile, Makefile
Accidentally left the `npm install` in the paas deployment. Fix that, and also optimise the Dockerfile slightly for better caching.
=> Don't npm install on paas

app/application.py, app/uploader/templates/form/input_radio_field.html, app/uploader/templates/pipeline_data_verify.html, app/uploader/utils.py, app/uploader/views.py, tests/uploader/test_utils.py, tests/uploader/test_views.py
We want to have some basic QA on uploaded CSVs, which in this case means
making sure that they're only alphanumeric with underscores - no
symbols, spaces, etc.
We also want to call attention to uploaded data that is backwards-incompatible with previous uploads, so that users have the opportunity to make informed decisions about whether or not their upload might break existing queries.
=> Add extra validation for uploaded data

app/uploader/templates/pipeline_data_upload.html, app/uploader/templates/pipeline_data_uploaded.html, app/uploader/views.py, tests/uploader/test_views.py
This patch adds a link back to the 'data processing progress' page from
the pipeline overview page. Previously it wasn't possible to get back to
this page through the UI (though you could hack the URL). Reloading the
'progress' page would also end up spawning a new processor thread,
meaning that the same data file could be processed multiple times. This
moves the spawning step to the validated POST, and leaves the 'GET
progress' view as just returning updates on how the processor is doing.
=> Return to upload progress

app/config/docker.yml, docker-compose.yml, requirements.in
This allows overriding all env vars by using a .env file when running the app locally via docker compose. This commit also deleted the docker.yml config file as any local configuration should be done via the .env file.
=> fix: set USE_DOTENV variable in docker-compose

app/commands/dev/datafiles_to_db_by_source.py, tests/commands/dev/test_datafiles_to_db_by_source.py
The world bank transform pipeline is always triggered on the run command independent if there is new
data available or not. Because this takes takes very long we want to trigger
it only if the transform flag is set explicitly in the command.
=> fix: worldbank transform trigger

.envs/docker.env, docker-compose.yml
When running data-store-service through docker-compose, make it use a
shared Data Infrastructure network so that, by default, all of our apps
can theoretically talk to each other. This may be useful e.g. when
running/testing uploads locally, as they rely on data-flow.
=> feat: use shared data infrastructure dev network

app/etl/pipeline_type/dsv_to_table.py, tests/etl/test_dsv_to_table.py, tests/fixtures/generic_dsv/country_list_dups.csv
`Data uploader` uses a snapshot pipeline that only saves unique rows. This PR changes the `DSVToTablePipeline` to incremental pipeline so as to save duplicate rows as wel.
=> change DSVToTablePipeline to incremental pipeline

app/application.py, app/db/models/internal.py, app/uploader/utils.py, migrations/versions/20201019_2237_ac7dbd72d46e_.py, tests/uploader/test_utils.py
A rudimentary implementation of a cleanup job that ensures pipelines
don't get stuck in "processing" step forever. This can happen right now
if the app instance dies while a data file is being processed (either by
data-store-service or data-flow), because the task is simply kicked off
as a background thread on the web worker and there is no retry/recovery
mechanism.
In the future we'll want to move to some more robust background job
handler (e.g. celery), but for now this service is only used within our
team and so that level of robustness is not required.
=> feat: clean up old pipeline processing tasks

Makefile, Procfile, README.md, app/application.py, app/commands/__init__.py, app/commands/scheduler.py
Gunicorn launches ~8 workers in our deployed environment now, and with
the current setup each of those will startup a background scheduler with
a copy of the tasks to run.
Let's use a separate CF process to run a single scheduler instance.
=> Move scheduler to separate CF process

app/uploader/utils.py
Now that this cleanup code has been out for a while, we can broaden the
conditions to check all historical pipelines as old ones without a
started_processing_at date will all be more than 24 hours old.
=> fix: clean up all pipelines

app/config/defaults.yml, app/downloader/inspector.py, requirements.in, requirements.txt
Downloading the chromedriver binary and configuring the path is no longer the recommended way to set it up. This can be done automatically using webdriver-manager. See https://stackoverflow.com/questions/29858752/error-message-chromedriver-executable-needs-to-be-available-in-the-path/52878725#52878725.
This should resolve the following sentry error we have started seeing recently.
https://sentry.ci.uktrade.digital/dit/data-store-service/issues/33921/?referrer=slack
=> feature: use webdriver-manager to select  the correct chrome driver

Procfile, app/downloader/inspector.py, scripts/fix_chromium_path.sh
... and telling webdriver-manager to use Chromium, rather than the default which is Google Chrome.
Suspect this was broken since https://github.com/uktrade/data-store-service/pull/262
=> fix: ONS postcode pipeline by correcting path to Chromium

Jenkinsfile
Data Store Service is not set up with automatic migrations currently,
because of some historical fears about some tables not being OK to
migrate automatically.
Until we can investigate that, let's at least put a reminder into the
pipeline so that people know it needs to be done manually/with thought.
=> fix: add prompt to run migrations

app/config/defaults.yml, app/uploader/csv_parser.py
Set the number of lines read in to infer data types in the environment (with fall back to the original, 100,000)
The reasoning for this is that the world bank data import is currently getting killed when attempting to read in 100k lines to infer data types.
=> feat: alow for configurable sample size

app/config/local_testing.yml, app/uploader/templates/pipeline_data_upload_failed.html, app/uploader/templates/pipeline_data_uploaded.html, app/uploader/views.py, tests/uploader/test_views.py
At the moment, pipeline failures are reported within a green Design
System panel component, which is the same pattern we use for success of
the pipeline. This makes it harder for users to understand the end
result of a pipeline because it's easy to scan the page, see the green
banner, and expect success. We add a separate page for failures states
here to highlight the issue and provide a recommendation - to try
ingesting again.
=> feat: add pipeline failure page

app/api/views/dit_reference_postcodes.py, app/api/views/get_table.py, app/etl/organisation/dit.py, app/etl/organisation/world_bank.py, app/etl/pipeline_type/base.py, app/etl/pipeline_type/incremental_data.py, app/etl/pipeline_type/snapshot_data.py, requirements.txt, tests/etl/test_world_bank_tariff.py
The data-engineering-common project, that is a dependency of this project, requires SQLAlchemy >= 2.0.0 as of https://github.com/uktrade/data-engineering-common/pull/34. So in order for this project to build successfully, we need SQLAlchemy >= 2.0.0
This was done by running (after a bit of trial and error):
```shell
pip-compile --upgrade-pacakge alembic --upgrade-package sqlalchemy-utils --upgrade-package pandas==2.1.2
```
Which involves breaking changes to both SQLAlchemy and Pandas. Specifically now it seems to be necessary to:
- Go via the "inspect" API in SQLAlchemy to check if a table exists
- Wrap all SQL strings with SQLAlchemy's `text`
- Use named parameters in SQL strings and dictionaries for their values.
=> fix: bump to SQLAlchemy 2 and related packages to allow to build and pass tests

Dockerfile, README.md, scripts/install_node.sh
The previous node version would not install (erroring with messages about unsupported versions), and was not the same as the one running in CircleCI. Just changing the existing script to the same node version as in CircleCI also errored out, so an alternative, and hopefully more robust way is used. This now seems to work fine locally.
This deliberately does away with the separate script to install node - this isn't needed and makes it harder to see what's going on when you need to change things.
This also updates the command to run locally `from docker-compose` to `docker compose`, which is the current recommended way to run compose file.
=> dev: make it possible again to run data-store-service locally

app/commands/dev/datafiles_to_s3_by_source.py, app/etl/organisation/companies_house.py, tests/commands/dev/test_datafiles_to_db_by_source.py, tests/commands/dev/test_datafiles_to_s3_by_source.py, tests/etl/test_companies_house_accounts.py
There is decreasing confidence in the older v1 Companies House accounts pipeline within the data-store-service, and so this will now ingest to a _legacy table in order to use the data for comparison, but to make the newer incremental pipeline ingest to the main accounts table. This means that the data ingested using stream-read-xbrl can be used within the Export Propensity pipeline.
=> feat: older CompaniesHouseAccounts pipeline ingest to _legacy table
